In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

url = "https://raw.githubusercontent.com/Alam-A99/DATAAKSI/main/dataset_fiskal_97_hipoFull.csv"
df = pd.read_csv(url)

Pemeriksaan Awal

In [3]:
print("\n--- 5 Baris Pertama ---")
display(df.head())

print("\n--- Informasi Struktur Dataset ---")
df.info()

print("\n--- Statistik Deskriptif (Kolom Numerik) ---")
display(df.describe())

--- 5 Baris Pertama ---

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52

--- Informasi Struktur Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Kota                    1067 non-null   str
 1   Tahun                   1067 non-null   int64
 2   DBH_PAJAK               1067 non-null   float64
 3   DBH_SDA                 1067 non-null   float64
 4   DBH_Lainnya             1067 non-null   float64
 5   DAU_Grant               1067 non-null   float64
 6   DAU_Earmark             1067 non-null   float64
 7   DAK_Fisik               1067 non-null   float64
 8   DAK_Nonfisik            1067 non-null   float64
 9   PAD                     1067 non-null   float64
 10  ICT                     1067 non-null   float64
 11  bm_pendidikan           1067 non-null   float64
 12  bm_kesehatan            1067 non-null   float64
 13  bm_perumahan            1067 non-null   float64
 14  bm_lingkungan           1067 non-null   float64
 15  bm_ekonomi              1067 non-null   float64
 16  bm_infrastruktur        1067 non-null   float64
 17  bm_pariwisata           1067 non-null   float64
 18  bm_perlindungan_sosial  1067 non-null   float64
 19  KEMISKINAN              1067 non-null   float64
 20  PENGANGGURAN            1067 non-null   float64
 21  KETIMPANGAN             1067 non-null   float64
 22  IPM                     1067 non-null   float64
 23  PE                      1067 non-null   float64
dtypes: float64(22), int64(1), str(1)
memory usage: 200.2 KB

--- Statistik Deskriptif (Kolom Numerik) ---

,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,ICT,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
count,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,...,1067.000000,1067.00000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2019.000000,107.905464,71.138960,53.830628,178.029850,107.452034,107.783393,106.766401,215.204077,81.898013,...,172.587882,173.69358,174.611565,172.471546,171.014255,12.538519,6.466692,0.398641,72.378847,4.958547
std,3.163761,57.856235,42.449883,28.680751,87.999498,54.994876,56.152152,56.852234,110.345873,11.873095,...,71.441473,72.10115,72.044194,71.984621,71.837922,4.258490,2.033596,0.057334,7.211382,1.668266
min,2014.000000,11.550000,5.940000,6.190000,22.330000,12.260000,12.710000,13.420000,24.060000,60.630000,...,50.010000,50.06000,50.980000,50.060000,50.060000,5.000000,3.000000,0.300000,60.010000,2.000000
25%,2016.000000,69.770000,42.840000,34.390000,118.675000,69.420000,68.740000,65.130000,138.570000,71.000000,...,109.455000,111.02500,111.405000,110.245000,108.400000,9.055000,4.750000,0.350000,66.075000,3.590000
50%,2019.000000,96.720000,61.830000,47.760000,163.550000,98.520000,99.410000,95.910000,198.420000,82.030000,...,171.960000,170.87000,174.580000,170.560000,168.840000,12.470000,6.390000,0.400000,72.420000,4.960000
75%,2022.000000,137.460000,90.070000,68.720000,223.535000,137.480000,134.720000,135.945000,273.040000,92.340000,...,232.870000,237.29000,235.460000,236.230000,231.505000,16.140000,8.235000,0.450000,78.765000,6.345000
max,2024.000000,365.020000,278.510000,166.720000,582.960000,303.090000,353.440000,381.840000,686.780000,100.000000,...,299.890000,299.70000,299.870000,299.800000,299.360000,19.990000,10.000000,0.500000,84.950000,7.990000

Menampilkan Kota

In [4]:
kota_sulsel = [
    "Kota Makassar",
    "Kota sinjai",
    "Kota bone"
]
df_sulsel = df[df["Kota"].isin(kota_sulsel)]

display(df_sulsel)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
825,Kota Makassar,2014,100.33,135.65,93.41,196.43,121.44,129.07,167.07,300.19,...,149.25,79.49,88.70,77.50,242.83,14.67,8.30,0.32,80.83,6.98
826,Kota Makassar,2015,157.59,138.85,84.94,219.97,142.85,149.27,105.43,390.58,...,89.08,61.29,125.29,286.86,260.36,6.93,7.88,0.40,60.64,4.52
827,Kota Makassar,2016,200.46,110.87,66.51,229.66,147.58,135.90,163.10,425.72,...,234.49,159.47,112.24,155.84,204.42,13.62,9.23,0.43,71.88,3.16
828,Kota Makassar,2017,167.97,156.24,73.72,243.02,211.80,181.22,215.66,442.44,...,140.12,261.00,143.08,52.33,211.11,5.80,6.51,0.37,75.65,3.71
829,Kota Makassar,2018,153.01,126.27,102.08,255.03,216.75,191.91,232.94,320.11,...,217.82,115.60,113.67,160.60,57.08,6.62,6.55,0.32,84.24,5.03
830,Kota Makassar,2019,183.32,107.17,71.54,215.97,169.59,165.73,133.91,399.41,...,117.66,155.43,172.24,61.52,257.13,9.56,6.15,0.41,62.51,5.19
831,Kota Makassar,2020,188.17,79.51,94.96,355.96,207.21,231.97,144.49,351.69,...,70.31,59.98,151.85,185.97,247.07,17.29,3.56,0.47,62.30,6.83
832,Kota Makassar,2021,190.75,155.91,80.80,289.63,170.45,158.10,183.97,424.56,...,298.15,162.27,296.64,134.64,114.76,13.83,8.53,0.43,75.22,6.75
833,Kota Makassar,2022,188.18,116.77,117.61,284.74,128.42,210.85,153.54,482.68,...,89.05,194.40,63.98,168.36,227.17,17.89,3.54,0.32,72.38,5.49
834,Kota Makassar,2023,180.93,172.69,113.17,329.93,145.52,248.38,172.39,520.69,...,297.11,192.73,85.55,203.29,103.71,11.30,7.04,0.47,81.59,6.68
835,Kota Makassar,2024,161.78,170.64,95.89,293.35,254.86,160.33,137.28,273.07,...,294.32,133.11,63.21,267.20,60.08,14.33,7.63,0.36,68.00,3.15

Print baris pilihan

In [5]:
print("--- 5 Baris Pertama ---")
display(df.head())

--- 5 Baris Pertama ---

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52

In [6]:
print("--- 5 Baris Terakhir ---")
display(df.head())

--- 5 Baris Terakhir ---

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52